# Generated by Django 4.0.6 on 2022-07-10 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_desc', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(help_text='same as username', max_length=6, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=55)),
                ('username', models.ForeignKey(help_text='same as student id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_RegistrationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.students')),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('instructor_id', models.CharField(help_text='same as username', max_length=6, primary_key=True, serialize=False)),
                ('instructor', models.CharField(max_length=55)),
                ('username', models.ForeignKey(help_text='same as instructor id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_RegistrationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.courses')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.instructors')),
            ],
        ),
    ]
