# Generated by Django 4.0.6 on 2022-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='credit',
            field=models.FloatField(blank=True, null=True, verbose_name='credits'),
        ),
    ]
