# Generated by Django 4.0.6 on 2022-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_courses_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructors',
            old_name='instructor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='courses',
            name='credit',
            field=models.FloatField(blank=True, default=0.0, verbose_name='credits'),
        ),
    ]
