# Generated by Django 4.0.6 on 2022-07-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=25)),
                ('weightage', models.FloatField(help_text='In percentage')),
                ('total_marks', models.FloatField()),
                ('marks', models.FloatField(blank=True, null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.courses')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.students')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.courses')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.students')),
            ],
        ),
    ]
