# Generated by Django 4.0.6 on 2022-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.FloatField(verbose_name='maximum marks'),
        ),
    ]
